AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'signalwire-client.gemspec'
    - 'Gemfile'
    - 'vendor/**/*'

Metrics/ClassLength:
  Max: 512

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 132

StringLiterals:
  EnforcedStyle: single_quotes

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ConditionalAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'Guardfile'

