AllCops:
  Exclude:
    - 'bin/**/*'
    - 'signalwire.gemspec'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'examples/**/*'
    - 'tmp/**/*'
    - 'lib/signalwire/rest/client.rb' # it is just a shim, and has a weird signature

Metrics/ClassLength:
  Max: 512

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 132

StringLiterals:
  EnforcedStyle: single_quotes

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

# Layout/AlignArguments:
#   Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'Guardfile'

